/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CertificateStatus;
import org.openapitools.client.model.CertificateType;
import org.openapitools.client.model.KeyAlgorithm;
import org.openapitools.client.model.RenewalEligibility;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CertificateSummary
 */
public class CertificateSummaryTest {
    private final CertificateSummary model = new CertificateSummary();

    /**
     * Model tests for CertificateSummary
     */
    @Test
    public void testCertificateSummary() {
        // TODO: test CertificateSummary
    }

    /**
     * Test the property 'certificateArn'
     */
    @Test
    public void certificateArnTest() {
        // TODO: test certificateArn
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'subjectAlternativeNameSummaries'
     */
    @Test
    public void subjectAlternativeNameSummariesTest() {
        // TODO: test subjectAlternativeNameSummaries
    }

    /**
     * Test the property 'hasAdditionalSubjectAlternativeNames'
     */
    @Test
    public void hasAdditionalSubjectAlternativeNamesTest() {
        // TODO: test hasAdditionalSubjectAlternativeNames
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'keyAlgorithm'
     */
    @Test
    public void keyAlgorithmTest() {
        // TODO: test keyAlgorithm
    }

    /**
     * Test the property 'keyUsages'
     */
    @Test
    public void keyUsagesTest() {
        // TODO: test keyUsages
    }

    /**
     * Test the property 'extendedKeyUsages'
     */
    @Test
    public void extendedKeyUsagesTest() {
        // TODO: test extendedKeyUsages
    }

    /**
     * Test the property 'inUse'
     */
    @Test
    public void inUseTest() {
        // TODO: test inUse
    }

    /**
     * Test the property 'exported'
     */
    @Test
    public void exportedTest() {
        // TODO: test exported
    }

    /**
     * Test the property 'renewalEligibility'
     */
    @Test
    public void renewalEligibilityTest() {
        // TODO: test renewalEligibility
    }

    /**
     * Test the property 'notBefore'
     */
    @Test
    public void notBeforeTest() {
        // TODO: test notBefore
    }

    /**
     * Test the property 'notAfter'
     */
    @Test
    public void notAfterTest() {
        // TODO: test notAfter
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'issuedAt'
     */
    @Test
    public void issuedAtTest() {
        // TODO: test issuedAt
    }

    /**
     * Test the property 'importedAt'
     */
    @Test
    public void importedAtTest() {
        // TODO: test importedAt
    }

    /**
     * Test the property 'revokedAt'
     */
    @Test
    public void revokedAtTest() {
        // TODO: test revokedAt
    }

}
