/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CertificateDetailOptions;
import org.openapitools.client.model.CertificateDetailRenewalSummary;
import org.openapitools.client.model.CertificateStatus;
import org.openapitools.client.model.CertificateType;
import org.openapitools.client.model.FailureReason;
import org.openapitools.client.model.KeyAlgorithm;
import org.openapitools.client.model.RenewalEligibility;
import org.openapitools.client.model.RevocationReason;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DescribeCertificateResponseCertificate
 */
public class DescribeCertificateResponseCertificateTest {
    private final DescribeCertificateResponseCertificate model = new DescribeCertificateResponseCertificate();

    /**
     * Model tests for DescribeCertificateResponseCertificate
     */
    @Test
    public void testDescribeCertificateResponseCertificate() {
        // TODO: test DescribeCertificateResponseCertificate
    }

    /**
     * Test the property 'certificateArn'
     */
    @Test
    public void certificateArnTest() {
        // TODO: test certificateArn
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'subjectAlternativeNames'
     */
    @Test
    public void subjectAlternativeNamesTest() {
        // TODO: test subjectAlternativeNames
    }

    /**
     * Test the property 'domainValidationOptions'
     */
    @Test
    public void domainValidationOptionsTest() {
        // TODO: test domainValidationOptions
    }

    /**
     * Test the property 'serial'
     */
    @Test
    public void serialTest() {
        // TODO: test serial
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'issuedAt'
     */
    @Test
    public void issuedAtTest() {
        // TODO: test issuedAt
    }

    /**
     * Test the property 'importedAt'
     */
    @Test
    public void importedAtTest() {
        // TODO: test importedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'revokedAt'
     */
    @Test
    public void revokedAtTest() {
        // TODO: test revokedAt
    }

    /**
     * Test the property 'revocationReason'
     */
    @Test
    public void revocationReasonTest() {
        // TODO: test revocationReason
    }

    /**
     * Test the property 'notBefore'
     */
    @Test
    public void notBeforeTest() {
        // TODO: test notBefore
    }

    /**
     * Test the property 'notAfter'
     */
    @Test
    public void notAfterTest() {
        // TODO: test notAfter
    }

    /**
     * Test the property 'keyAlgorithm'
     */
    @Test
    public void keyAlgorithmTest() {
        // TODO: test keyAlgorithm
    }

    /**
     * Test the property 'signatureAlgorithm'
     */
    @Test
    public void signatureAlgorithmTest() {
        // TODO: test signatureAlgorithm
    }

    /**
     * Test the property 'inUseBy'
     */
    @Test
    public void inUseByTest() {
        // TODO: test inUseBy
    }

    /**
     * Test the property 'failureReason'
     */
    @Test
    public void failureReasonTest() {
        // TODO: test failureReason
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'renewalSummary'
     */
    @Test
    public void renewalSummaryTest() {
        // TODO: test renewalSummary
    }

    /**
     * Test the property 'keyUsages'
     */
    @Test
    public void keyUsagesTest() {
        // TODO: test keyUsages
    }

    /**
     * Test the property 'extendedKeyUsages'
     */
    @Test
    public void extendedKeyUsagesTest() {
        // TODO: test extendedKeyUsages
    }

    /**
     * Test the property 'certificateAuthorityArn'
     */
    @Test
    public void certificateAuthorityArnTest() {
        // TODO: test certificateAuthorityArn
    }

    /**
     * Test the property 'renewalEligibility'
     */
    @Test
    public void renewalEligibilityTest() {
        // TODO: test renewalEligibility
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

}
