/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DomainStatus;
import org.openapitools.client.model.DomainValidationResourceRecord;
import org.openapitools.client.model.ValidationMethod;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DomainValidation
 */
public class DomainValidationTest {
    private final DomainValidation model = new DomainValidation();

    /**
     * Model tests for DomainValidation
     */
    @Test
    public void testDomainValidation() {
        // TODO: test DomainValidation
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'validationEmails'
     */
    @Test
    public void validationEmailsTest() {
        // TODO: test validationEmails
    }

    /**
     * Test the property 'validationDomain'
     */
    @Test
    public void validationDomainTest() {
        // TODO: test validationDomain
    }

    /**
     * Test the property 'validationStatus'
     */
    @Test
    public void validationStatusTest() {
        // TODO: test validationStatus
    }

    /**
     * Test the property 'resourceRecord'
     */
    @Test
    public void resourceRecordTest() {
        // TODO: test resourceRecord
    }

    /**
     * Test the property 'validationMethod'
     */
    @Test
    public void validationMethodTest() {
        // TODO: test validationMethod
    }

}
