/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListCertificatesRequestIncludes;
import org.openapitools.client.model.SortBy;
import org.openapitools.client.model.SortOrder;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListCertificatesRequest
 */
public class ListCertificatesRequestTest {
    private final ListCertificatesRequest model = new ListCertificatesRequest();

    /**
     * Model tests for ListCertificatesRequest
     */
    @Test
    public void testListCertificatesRequest() {
        // TODO: test ListCertificatesRequest
    }

    /**
     * Test the property 'certificateStatuses'
     */
    @Test
    public void certificateStatusesTest() {
        // TODO: test certificateStatuses
    }

    /**
     * Test the property 'includes'
     */
    @Test
    public void includesTest() {
        // TODO: test includes
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'maxItems'
     */
    @Test
    public void maxItemsTest() {
        // TODO: test maxItems
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

}
