/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListCertificatesRequestIncludes
 */
public class ListCertificatesRequestIncludesTest {
    private final ListCertificatesRequestIncludes model = new ListCertificatesRequestIncludes();

    /**
     * Model tests for ListCertificatesRequestIncludes
     */
    @Test
    public void testListCertificatesRequestIncludes() {
        // TODO: test ListCertificatesRequestIncludes
    }

    /**
     * Test the property 'extendedKeyUsage'
     */
    @Test
    public void extendedKeyUsageTest() {
        // TODO: test extendedKeyUsage
    }

    /**
     * Test the property 'keyUsage'
     */
    @Test
    public void keyUsageTest() {
        // TODO: test keyUsage
    }

    /**
     * Test the property 'keyTypes'
     */
    @Test
    public void keyTypesTest() {
        // TODO: test keyTypes
    }

}
