/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PutAccountConfigurationRequestExpiryEvents;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PutAccountConfigurationRequest
 */
public class PutAccountConfigurationRequestTest {
    private final PutAccountConfigurationRequest model = new PutAccountConfigurationRequest();

    /**
     * Model tests for PutAccountConfigurationRequest
     */
    @Test
    public void testPutAccountConfigurationRequest() {
        // TODO: test PutAccountConfigurationRequest
    }

    /**
     * Test the property 'expiryEvents'
     */
    @Test
    public void expiryEventsTest() {
        // TODO: test expiryEvents
    }

    /**
     * Test the property 'idempotencyToken'
     */
    @Test
    public void idempotencyTokenTest() {
        // TODO: test idempotencyToken
    }

}
