/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.KeyAlgorithm;
import org.openapitools.client.model.RequestCertificateRequestOptions;
import org.openapitools.client.model.ValidationMethod;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestCertificateRequest
 */
public class RequestCertificateRequestTest {
    private final RequestCertificateRequest model = new RequestCertificateRequest();

    /**
     * Model tests for RequestCertificateRequest
     */
    @Test
    public void testRequestCertificateRequest() {
        // TODO: test RequestCertificateRequest
    }

    /**
     * Test the property 'domainName'
     */
    @Test
    public void domainNameTest() {
        // TODO: test domainName
    }

    /**
     * Test the property 'validationMethod'
     */
    @Test
    public void validationMethodTest() {
        // TODO: test validationMethod
    }

    /**
     * Test the property 'subjectAlternativeNames'
     */
    @Test
    public void subjectAlternativeNamesTest() {
        // TODO: test subjectAlternativeNames
    }

    /**
     * Test the property 'idempotencyToken'
     */
    @Test
    public void idempotencyTokenTest() {
        // TODO: test idempotencyToken
    }

    /**
     * Test the property 'domainValidationOptions'
     */
    @Test
    public void domainValidationOptionsTest() {
        // TODO: test domainValidationOptions
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'certificateAuthorityArn'
     */
    @Test
    public void certificateAuthorityArnTest() {
        // TODO: test certificateAuthorityArn
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'keyAlgorithm'
     */
    @Test
    public void keyAlgorithmTest() {
        // TODO: test keyAlgorithm
    }

}
