/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CertificateTransparencyLoggingPreference;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestCertificateRequestOptions
 */
public class RequestCertificateRequestOptionsTest {
    private final RequestCertificateRequestOptions model = new RequestCertificateRequestOptions();

    /**
     * Model tests for RequestCertificateRequestOptions
     */
    @Test
    public void testRequestCertificateRequestOptions() {
        // TODO: test RequestCertificateRequestOptions
    }

    /**
     * Test the property 'certificateTransparencyLoggingPreference'
     */
    @Test
    public void certificateTransparencyLoggingPreferenceTest() {
        // TODO: test certificateTransparencyLoggingPreference
    }

}
