/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResendValidationEmailRequest
 */
public class ResendValidationEmailRequestTest {
    private final ResendValidationEmailRequest model = new ResendValidationEmailRequest();

    /**
     * Model tests for ResendValidationEmailRequest
     */
    @Test
    public void testResendValidationEmailRequest() {
        // TODO: test ResendValidationEmailRequest
    }

    /**
     * Test the property 'certificateArn'
     */
    @Test
    public void certificateArnTest() {
        // TODO: test certificateArn
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'validationDomain'
     */
    @Test
    public void validationDomainTest() {
        // TODO: test validationDomain
    }

}
