package main

import (
	"github.com/aws-certificate-manager/mcp-server/config"
	"github.com/aws-certificate-manager/mcp-server/models"
	tools_x_amz_target_certificatemanager_listtagsforcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_listtagsforcertificate"
	tools_x_amz_target_certificatemanager_requestcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_requestcertificate"
	tools_x_amz_target_certificatemanager_resendvalidationemail "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_resendvalidationemail"
	tools_x_amz_target_certificatemanager_listcertificates "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_listcertificates"
	tools_x_amz_target_certificatemanager_updatecertificateoptions "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_updatecertificateoptions"
	tools_x_amz_target_certificatemanager_deletecertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_deletecertificate"
	tools_x_amz_target_certificatemanager_getcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_getcertificate"
	tools_x_amz_target_certificatemanager_putaccountconfiguration "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_putaccountconfiguration"
	tools_x_amz_target_certificatemanager_addtagstocertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_addtagstocertificate"
	tools_x_amz_target_certificatemanager_getaccountconfiguration "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_getaccountconfiguration"
	tools_x_amz_target_certificatemanager_importcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_importcertificate"
	tools_x_amz_target_certificatemanager_describecertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_describecertificate"
	tools_x_amz_target_certificatemanager_renewcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_renewcertificate"
	tools_x_amz_target_certificatemanager_exportcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_exportcertificate"
	tools_x_amz_target_certificatemanager_removetagsfromcertificate "github.com/aws-certificate-manager/mcp-server/tools/x_amz_target_certificatemanager_removetagsfromcertificate"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_certificatemanager_listtagsforcertificate.CreateListtagsforcertificateTool(cfg),
		tools_x_amz_target_certificatemanager_requestcertificate.CreateRequestcertificateTool(cfg),
		tools_x_amz_target_certificatemanager_resendvalidationemail.CreateResendvalidationemailTool(cfg),
		tools_x_amz_target_certificatemanager_listcertificates.CreateListcertificatesTool(cfg),
		tools_x_amz_target_certificatemanager_updatecertificateoptions.CreateUpdatecertificateoptionsTool(cfg),
		tools_x_amz_target_certificatemanager_deletecertificate.CreateDeletecertificateTool(cfg),
		tools_x_amz_target_certificatemanager_getcertificate.CreateGetcertificateTool(cfg),
		tools_x_amz_target_certificatemanager_putaccountconfiguration.CreatePutaccountconfigurationTool(cfg),
		tools_x_amz_target_certificatemanager_addtagstocertificate.CreateAddtagstocertificateTool(cfg),
		tools_x_amz_target_certificatemanager_getaccountconfiguration.CreateGetaccountconfigurationTool(cfg),
		tools_x_amz_target_certificatemanager_importcertificate.CreateImportcertificateTool(cfg),
		tools_x_amz_target_certificatemanager_describecertificate.CreateDescribecertificateTool(cfg),
		tools_x_amz_target_certificatemanager_renewcertificate.CreateRenewcertificateTool(cfg),
		tools_x_amz_target_certificatemanager_exportcertificate.CreateExportcertificateTool(cfg),
		tools_x_amz_target_certificatemanager_removetagsfromcertificate.CreateRemovetagsfromcertificateTool(cfg),
	}
}
