/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CertificateStatus
 */
@JsonAdapter(CertificateStatus.Adapter.class)
public enum CertificateStatus {
  
  PENDING_VALIDATION("PENDING_VALIDATION"),
  
  ISSUED("ISSUED"),
  
  INACTIVE("INACTIVE"),
  
  EXPIRED("EXPIRED"),
  
  VALIDATION_TIMED_OUT("VALIDATION_TIMED_OUT"),
  
  REVOKED("REVOKED"),
  
  FAILED("FAILED");

  private String value;

  CertificateStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CertificateStatus fromValue(String value) {
    for (CertificateStatus b : CertificateStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CertificateStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final CertificateStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CertificateStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CertificateStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CertificateStatus.fromValue(value);
  }
}

