/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CertificateTransparencyLoggingPreference
 */
@JsonAdapter(CertificateTransparencyLoggingPreference.Adapter.class)
public enum CertificateTransparencyLoggingPreference {
  
  ENABLED("ENABLED"),
  
  DISABLED("DISABLED");

  private String value;

  CertificateTransparencyLoggingPreference(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CertificateTransparencyLoggingPreference fromValue(String value) {
    for (CertificateTransparencyLoggingPreference b : CertificateTransparencyLoggingPreference.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CertificateTransparencyLoggingPreference> {
    @Override
    public void write(final JsonWriter jsonWriter, final CertificateTransparencyLoggingPreference enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CertificateTransparencyLoggingPreference read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CertificateTransparencyLoggingPreference.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CertificateTransparencyLoggingPreference.fromValue(value);
  }
}

