/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Object containing expiration events options associated with an Amazon Web Services account.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:24.052488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ExpiryEventsConfiguration {
  public static final String SERIALIZED_NAME_DAYS_BEFORE_EXPIRY = "DaysBeforeExpiry";
  @SerializedName(SERIALIZED_NAME_DAYS_BEFORE_EXPIRY)
  @javax.annotation.Nullable
  private Integer daysBeforeExpiry;

  public ExpiryEventsConfiguration() {
  }

  public ExpiryEventsConfiguration daysBeforeExpiry(@javax.annotation.Nullable Integer daysBeforeExpiry) {
    this.daysBeforeExpiry = daysBeforeExpiry;
    return this;
  }

  /**
   * Get daysBeforeExpiry
   * @return daysBeforeExpiry
   */
  @javax.annotation.Nullable
  public Integer getDaysBeforeExpiry() {
    return daysBeforeExpiry;
  }

  public void setDaysBeforeExpiry(@javax.annotation.Nullable Integer daysBeforeExpiry) {
    this.daysBeforeExpiry = daysBeforeExpiry;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpiryEventsConfiguration expiryEventsConfiguration = (ExpiryEventsConfiguration) o;
    return Objects.equals(this.daysBeforeExpiry, expiryEventsConfiguration.daysBeforeExpiry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(daysBeforeExpiry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpiryEventsConfiguration {\n");
    sb.append("    daysBeforeExpiry: ").append(toIndentedString(daysBeforeExpiry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DaysBeforeExpiry");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ExpiryEventsConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExpiryEventsConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpiryEventsConfiguration is not found in the empty JSON string", ExpiryEventsConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExpiryEventsConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExpiryEventsConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `DaysBeforeExpiry`
      if (jsonObj.get("DaysBeforeExpiry") != null && !jsonObj.get("DaysBeforeExpiry").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("DaysBeforeExpiry"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpiryEventsConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpiryEventsConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpiryEventsConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpiryEventsConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpiryEventsConfiguration>() {
           @Override
           public void write(JsonWriter out, ExpiryEventsConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpiryEventsConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ExpiryEventsConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ExpiryEventsConfiguration
   * @throws IOException if the JSON string is invalid with respect to ExpiryEventsConfiguration
   */
  public static ExpiryEventsConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpiryEventsConfiguration.class);
  }

  /**
   * Convert an instance of ExpiryEventsConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

