/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ExtendedKeyUsageName
 */
@JsonAdapter(ExtendedKeyUsageName.Adapter.class)
public enum ExtendedKeyUsageName {
  
  TLS_WEB_SERVER_AUTHENTICATION("TLS_WEB_SERVER_AUTHENTICATION"),
  
  TLS_WEB_CLIENT_AUTHENTICATION("TLS_WEB_CLIENT_AUTHENTICATION"),
  
  CODE_SIGNING("CODE_SIGNING"),
  
  EMAIL_PROTECTION("EMAIL_PROTECTION"),
  
  TIME_STAMPING("TIME_STAMPING"),
  
  OCSP_SIGNING("OCSP_SIGNING"),
  
  IPSEC_END_SYSTEM("IPSEC_END_SYSTEM"),
  
  IPSEC_TUNNEL("IPSEC_TUNNEL"),
  
  IPSEC_USER("IPSEC_USER"),
  
  ANY("ANY"),
  
  NONE("NONE"),
  
  CUSTOM("CUSTOM");

  private String value;

  ExtendedKeyUsageName(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ExtendedKeyUsageName fromValue(String value) {
    for (ExtendedKeyUsageName b : ExtendedKeyUsageName.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ExtendedKeyUsageName> {
    @Override
    public void write(final JsonWriter jsonWriter, final ExtendedKeyUsageName enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ExtendedKeyUsageName read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ExtendedKeyUsageName.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ExtendedKeyUsageName.fromValue(value);
  }
}

