/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * This structure can be used in the &lt;a&gt;ListCertificates&lt;/a&gt; action to filter the output of the certificate list. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:24.052488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class Filters {
  public static final String SERIALIZED_NAME_EXTENDED_KEY_USAGE = "extendedKeyUsage";
  @SerializedName(SERIALIZED_NAME_EXTENDED_KEY_USAGE)
  @javax.annotation.Nullable
  private List extendedKeyUsage;

  public static final String SERIALIZED_NAME_KEY_USAGE = "keyUsage";
  @SerializedName(SERIALIZED_NAME_KEY_USAGE)
  @javax.annotation.Nullable
  private List keyUsage;

  public static final String SERIALIZED_NAME_KEY_TYPES = "keyTypes";
  @SerializedName(SERIALIZED_NAME_KEY_TYPES)
  @javax.annotation.Nullable
  private List keyTypes;

  public Filters() {
  }

  public Filters extendedKeyUsage(@javax.annotation.Nullable List extendedKeyUsage) {
    this.extendedKeyUsage = extendedKeyUsage;
    return this;
  }

  /**
   * Get extendedKeyUsage
   * @return extendedKeyUsage
   */
  @javax.annotation.Nullable
  public List getExtendedKeyUsage() {
    return extendedKeyUsage;
  }

  public void setExtendedKeyUsage(@javax.annotation.Nullable List extendedKeyUsage) {
    this.extendedKeyUsage = extendedKeyUsage;
  }


  public Filters keyUsage(@javax.annotation.Nullable List keyUsage) {
    this.keyUsage = keyUsage;
    return this;
  }

  /**
   * Get keyUsage
   * @return keyUsage
   */
  @javax.annotation.Nullable
  public List getKeyUsage() {
    return keyUsage;
  }

  public void setKeyUsage(@javax.annotation.Nullable List keyUsage) {
    this.keyUsage = keyUsage;
  }


  public Filters keyTypes(@javax.annotation.Nullable List keyTypes) {
    this.keyTypes = keyTypes;
    return this;
  }

  /**
   * Get keyTypes
   * @return keyTypes
   */
  @javax.annotation.Nullable
  public List getKeyTypes() {
    return keyTypes;
  }

  public void setKeyTypes(@javax.annotation.Nullable List keyTypes) {
    this.keyTypes = keyTypes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Filters filters = (Filters) o;
    return Objects.equals(this.extendedKeyUsage, filters.extendedKeyUsage) &&
        Objects.equals(this.keyUsage, filters.keyUsage) &&
        Objects.equals(this.keyTypes, filters.keyTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extendedKeyUsage, keyUsage, keyTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Filters {\n");
    sb.append("    extendedKeyUsage: ").append(toIndentedString(extendedKeyUsage)).append("\n");
    sb.append("    keyUsage: ").append(toIndentedString(keyUsage)).append("\n");
    sb.append("    keyTypes: ").append(toIndentedString(keyTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("extendedKeyUsage");
    openapiFields.add("keyUsage");
    openapiFields.add("keyTypes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Filters
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Filters.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Filters is not found in the empty JSON string", Filters.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Filters.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Filters` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `extendedKeyUsage`
      if (jsonObj.get("extendedKeyUsage") != null && !jsonObj.get("extendedKeyUsage").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("extendedKeyUsage"));
      }
      // validate the optional field `keyUsage`
      if (jsonObj.get("keyUsage") != null && !jsonObj.get("keyUsage").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("keyUsage"));
      }
      // validate the optional field `keyTypes`
      if (jsonObj.get("keyTypes") != null && !jsonObj.get("keyTypes").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("keyTypes"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Filters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Filters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Filters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Filters.class));

       return (TypeAdapter<T>) new TypeAdapter<Filters>() {
           @Override
           public void write(JsonWriter out, Filters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Filters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Filters given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Filters
   * @throws IOException if the JSON string is invalid with respect to Filters
   */
  public static Filters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Filters.class);
  }

  /**
   * Convert an instance of Filters to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

