/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets KeyUsageName
 */
@JsonAdapter(KeyUsageName.Adapter.class)
public enum KeyUsageName {
  
  DIGITAL_SIGNATURE("DIGITAL_SIGNATURE"),
  
  NON_REPUDIATION("NON_REPUDIATION"),
  
  KEY_ENCIPHERMENT("KEY_ENCIPHERMENT"),
  
  DATA_ENCIPHERMENT("DATA_ENCIPHERMENT"),
  
  KEY_AGREEMENT("KEY_AGREEMENT"),
  
  CERTIFICATE_SIGNING("CERTIFICATE_SIGNING"),
  
  CRL_SIGNING("CRL_SIGNING"),
  
  ENCIPHER_ONLY("ENCIPHER_ONLY"),
  
  DECIPHER_ONLY("DECIPHER_ONLY"),
  
  ANY("ANY"),
  
  CUSTOM("CUSTOM");

  private String value;

  KeyUsageName(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static KeyUsageName fromValue(String value) {
    for (KeyUsageName b : KeyUsageName.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<KeyUsageName> {
    @Override
    public void write(final JsonWriter jsonWriter, final KeyUsageName enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public KeyUsageName read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return KeyUsageName.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    KeyUsageName.fromValue(value);
  }
}

