/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListCertificatesRequestIncludes;
import org.openapitools.client.model.SortBy;
import org.openapitools.client.model.SortOrder;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListCertificatesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:24.052488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListCertificatesRequest {
  public static final String SERIALIZED_NAME_CERTIFICATE_STATUSES = "CertificateStatuses";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_STATUSES)
  @javax.annotation.Nullable
  private List certificateStatuses;

  public static final String SERIALIZED_NAME_INCLUDES = "Includes";
  @SerializedName(SERIALIZED_NAME_INCLUDES)
  @javax.annotation.Nullable
  private ListCertificatesRequestIncludes includes;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public static final String SERIALIZED_NAME_MAX_ITEMS = "MaxItems";
  @SerializedName(SERIALIZED_NAME_MAX_ITEMS)
  @javax.annotation.Nullable
  private Integer maxItems;

  public static final String SERIALIZED_NAME_SORT_BY = "SortBy";
  @SerializedName(SERIALIZED_NAME_SORT_BY)
  @javax.annotation.Nullable
  private SortBy sortBy;

  public static final String SERIALIZED_NAME_SORT_ORDER = "SortOrder";
  @SerializedName(SERIALIZED_NAME_SORT_ORDER)
  @javax.annotation.Nullable
  private SortOrder sortOrder;

  public ListCertificatesRequest() {
  }

  public ListCertificatesRequest certificateStatuses(@javax.annotation.Nullable List certificateStatuses) {
    this.certificateStatuses = certificateStatuses;
    return this;
  }

  /**
   * Get certificateStatuses
   * @return certificateStatuses
   */
  @javax.annotation.Nullable
  public List getCertificateStatuses() {
    return certificateStatuses;
  }

  public void setCertificateStatuses(@javax.annotation.Nullable List certificateStatuses) {
    this.certificateStatuses = certificateStatuses;
  }


  public ListCertificatesRequest includes(@javax.annotation.Nullable ListCertificatesRequestIncludes includes) {
    this.includes = includes;
    return this;
  }

  /**
   * Get includes
   * @return includes
   */
  @javax.annotation.Nullable
  public ListCertificatesRequestIncludes getIncludes() {
    return includes;
  }

  public void setIncludes(@javax.annotation.Nullable ListCertificatesRequestIncludes includes) {
    this.includes = includes;
  }


  public ListCertificatesRequest nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  public ListCertificatesRequest maxItems(@javax.annotation.Nullable Integer maxItems) {
    this.maxItems = maxItems;
    return this;
  }

  /**
   * Get maxItems
   * @return maxItems
   */
  @javax.annotation.Nullable
  public Integer getMaxItems() {
    return maxItems;
  }

  public void setMaxItems(@javax.annotation.Nullable Integer maxItems) {
    this.maxItems = maxItems;
  }


  public ListCertificatesRequest sortBy(@javax.annotation.Nullable SortBy sortBy) {
    this.sortBy = sortBy;
    return this;
  }

  /**
   * Get sortBy
   * @return sortBy
   */
  @javax.annotation.Nullable
  public SortBy getSortBy() {
    return sortBy;
  }

  public void setSortBy(@javax.annotation.Nullable SortBy sortBy) {
    this.sortBy = sortBy;
  }


  public ListCertificatesRequest sortOrder(@javax.annotation.Nullable SortOrder sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

  /**
   * Get sortOrder
   * @return sortOrder
   */
  @javax.annotation.Nullable
  public SortOrder getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(@javax.annotation.Nullable SortOrder sortOrder) {
    this.sortOrder = sortOrder;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListCertificatesRequest listCertificatesRequest = (ListCertificatesRequest) o;
    return Objects.equals(this.certificateStatuses, listCertificatesRequest.certificateStatuses) &&
        Objects.equals(this.includes, listCertificatesRequest.includes) &&
        Objects.equals(this.nextToken, listCertificatesRequest.nextToken) &&
        Objects.equals(this.maxItems, listCertificatesRequest.maxItems) &&
        Objects.equals(this.sortBy, listCertificatesRequest.sortBy) &&
        Objects.equals(this.sortOrder, listCertificatesRequest.sortOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateStatuses, includes, nextToken, maxItems, sortBy, sortOrder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCertificatesRequest {\n");
    sb.append("    certificateStatuses: ").append(toIndentedString(certificateStatuses)).append("\n");
    sb.append("    includes: ").append(toIndentedString(includes)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    maxItems: ").append(toIndentedString(maxItems)).append("\n");
    sb.append("    sortBy: ").append(toIndentedString(sortBy)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CertificateStatuses");
    openapiFields.add("Includes");
    openapiFields.add("NextToken");
    openapiFields.add("MaxItems");
    openapiFields.add("SortBy");
    openapiFields.add("SortOrder");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListCertificatesRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListCertificatesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListCertificatesRequest is not found in the empty JSON string", ListCertificatesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListCertificatesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListCertificatesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `CertificateStatuses`
      if (jsonObj.get("CertificateStatuses") != null && !jsonObj.get("CertificateStatuses").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("CertificateStatuses"));
      }
      // validate the optional field `Includes`
      if (jsonObj.get("Includes") != null && !jsonObj.get("Includes").isJsonNull()) {
        ListCertificatesRequestIncludes.validateJsonElement(jsonObj.get("Includes"));
      }
      // validate the optional field `NextToken`
      if (jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NextToken"));
      }
      // validate the optional field `MaxItems`
      if (jsonObj.get("MaxItems") != null && !jsonObj.get("MaxItems").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("MaxItems"));
      }
      // validate the optional field `SortBy`
      if (jsonObj.get("SortBy") != null && !jsonObj.get("SortBy").isJsonNull()) {
        SortBy.validateJsonElement(jsonObj.get("SortBy"));
      }
      // validate the optional field `SortOrder`
      if (jsonObj.get("SortOrder") != null && !jsonObj.get("SortOrder").isJsonNull()) {
        SortOrder.validateJsonElement(jsonObj.get("SortOrder"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListCertificatesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListCertificatesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListCertificatesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListCertificatesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ListCertificatesRequest>() {
           @Override
           public void write(JsonWriter out, ListCertificatesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListCertificatesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListCertificatesRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListCertificatesRequest
   * @throws IOException if the JSON string is invalid with respect to ListCertificatesRequest
   */
  public static ListCertificatesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListCertificatesRequest.class);
  }

  /**
   * Convert an instance of ListCertificatesRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

