/*
 * AWS Certificate Manager
 * <fullname>Certificate Manager</fullname> <p>You can use Certificate Manager (ACM) to manage SSL/TLS certificates for your Amazon Web Services-based websites and applications. For more information about using ACM, see the <a href=\"https://docs.aws.amazon.com/acm/latest/userguide/\">Certificate Manager User Guide</a>.</p>
 *
 * The version of the OpenAPI document: 2015-12-08
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FailureReason;
import org.openapitools.client.model.RenewalStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Contains information about the status of ACM&#39;s &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/acm/latest/userguide/acm-renewal.html\&quot;&gt;managed renewal&lt;/a&gt; for the certificate. This structure exists only when the certificate type is &lt;code&gt;AMAZON_ISSUED&lt;/code&gt;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:24.052488+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class RenewalSummary {
  public static final String SERIALIZED_NAME_RENEWAL_STATUS = "RenewalStatus";
  @SerializedName(SERIALIZED_NAME_RENEWAL_STATUS)
  @javax.annotation.Nonnull
  private RenewalStatus renewalStatus;

  public static final String SERIALIZED_NAME_DOMAIN_VALIDATION_OPTIONS = "DomainValidationOptions";
  @SerializedName(SERIALIZED_NAME_DOMAIN_VALIDATION_OPTIONS)
  @javax.annotation.Nonnull
  private List domainValidationOptions;

  public static final String SERIALIZED_NAME_RENEWAL_STATUS_REASON = "RenewalStatusReason";
  @SerializedName(SERIALIZED_NAME_RENEWAL_STATUS_REASON)
  @javax.annotation.Nullable
  private FailureReason renewalStatusReason;

  public static final String SERIALIZED_NAME_UPDATED_AT = "UpdatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public RenewalSummary() {
  }

  public RenewalSummary renewalStatus(@javax.annotation.Nonnull RenewalStatus renewalStatus) {
    this.renewalStatus = renewalStatus;
    return this;
  }

  /**
   * Get renewalStatus
   * @return renewalStatus
   */
  @javax.annotation.Nonnull
  public RenewalStatus getRenewalStatus() {
    return renewalStatus;
  }

  public void setRenewalStatus(@javax.annotation.Nonnull RenewalStatus renewalStatus) {
    this.renewalStatus = renewalStatus;
  }


  public RenewalSummary domainValidationOptions(@javax.annotation.Nonnull List domainValidationOptions) {
    this.domainValidationOptions = domainValidationOptions;
    return this;
  }

  /**
   * Get domainValidationOptions
   * @return domainValidationOptions
   */
  @javax.annotation.Nonnull
  public List getDomainValidationOptions() {
    return domainValidationOptions;
  }

  public void setDomainValidationOptions(@javax.annotation.Nonnull List domainValidationOptions) {
    this.domainValidationOptions = domainValidationOptions;
  }


  public RenewalSummary renewalStatusReason(@javax.annotation.Nullable FailureReason renewalStatusReason) {
    this.renewalStatusReason = renewalStatusReason;
    return this;
  }

  /**
   * Get renewalStatusReason
   * @return renewalStatusReason
   */
  @javax.annotation.Nullable
  public FailureReason getRenewalStatusReason() {
    return renewalStatusReason;
  }

  public void setRenewalStatusReason(@javax.annotation.Nullable FailureReason renewalStatusReason) {
    this.renewalStatusReason = renewalStatusReason;
  }


  public RenewalSummary updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RenewalSummary renewalSummary = (RenewalSummary) o;
    return Objects.equals(this.renewalStatus, renewalSummary.renewalStatus) &&
        Objects.equals(this.domainValidationOptions, renewalSummary.domainValidationOptions) &&
        Objects.equals(this.renewalStatusReason, renewalSummary.renewalStatusReason) &&
        Objects.equals(this.updatedAt, renewalSummary.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(renewalStatus, domainValidationOptions, renewalStatusReason, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RenewalSummary {\n");
    sb.append("    renewalStatus: ").append(toIndentedString(renewalStatus)).append("\n");
    sb.append("    domainValidationOptions: ").append(toIndentedString(domainValidationOptions)).append("\n");
    sb.append("    renewalStatusReason: ").append(toIndentedString(renewalStatusReason)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RenewalStatus");
    openapiFields.add("DomainValidationOptions");
    openapiFields.add("RenewalStatusReason");
    openapiFields.add("UpdatedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("RenewalStatus");
    openapiRequiredFields.add("DomainValidationOptions");
    openapiRequiredFields.add("UpdatedAt");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RenewalSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RenewalSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RenewalSummary is not found in the empty JSON string", RenewalSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RenewalSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RenewalSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RenewalSummary.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `RenewalStatus`
      RenewalStatus.validateJsonElement(jsonObj.get("RenewalStatus"));
      // validate the required field `DomainValidationOptions`
      List.validateJsonElement(jsonObj.get("DomainValidationOptions"));
      // validate the optional field `RenewalStatusReason`
      if (jsonObj.get("RenewalStatusReason") != null && !jsonObj.get("RenewalStatusReason").isJsonNull()) {
        FailureReason.validateJsonElement(jsonObj.get("RenewalStatusReason"));
      }
      // validate the required field `UpdatedAt`
      OffsetDateTime.validateJsonElement(jsonObj.get("UpdatedAt"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RenewalSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RenewalSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RenewalSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RenewalSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<RenewalSummary>() {
           @Override
           public void write(JsonWriter out, RenewalSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RenewalSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RenewalSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RenewalSummary
   * @throws IOException if the JSON string is invalid with respect to RenewalSummary
   */
  public static RenewalSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RenewalSummary.class);
  }

  /**
   * Convert an instance of RenewalSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

